Adds the ability to change the localization of names and descriptions of slash commands depending on the language in discord.
Chew/JDA-Chewtils pull request #78
Opened 2022-10-01 11:26 UTC by ZephyrKaOne

[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing
[pull-request]: https://github.com/JDA-Applications/JDA-Utilities/pulls

## Pull Request

#### Pull Request Checklist
Please follow the following steps before opening this PR.<br>
PRs that do not complete the checklist will be subject to denial for
missing information.

- [ ] I have checked the [pull request page][pull-request] for upcoming
      or merged features/bug fixes.
- [ ] I have read JDA's [contributing guidelines][contributing].

#### Pull Request Information
Check and fill in the blanks for all that apply:

- [ ] My PR fixes a bug, error, or other issue with the library's codebase.
- [ ] My PR is for the `______` module of the JDA-Utilities library.
- [ ] My PR creates a new module for the JDA-Utilities library: `______`.

#### Description

Describe your PR here.

2022-10-01 17:14 UTC, Chew requested changes
Great work! I'll need to do some testing then we'll be good to go.

I may want a helper to help make the locales, but we'll see.

2022-10-01 17:14 UTC, Chew commented on command/src/main/java/com/jagrosh/jdautilities/command/SlashCommand.java
> +
Docs

2022-10-01 17:14 UTC, Chew commented on command/src/main/java/com/jagrosh/jdautilities/command/SlashCommand.java
> +
Docs

2022-10-01 17:14 UTC, Chew commented on command/src/main/java/com/jagrosh/jdautilities/command/SlashCommand.java
> +
Docs

2022-10-01 17:14 UTC, Chew commented on command/src/main/java/com/jagrosh/jdautilities/command/SlashCommand.java
> +
Docs

2022-10-01 17:15 UTC, Chew commented
Do menus also have locales?

2022-10-02 12:22 UTC, ZephyrKaOne commented
> Do menus also have locales?

No, today I will do the same for the menu and write the docs.

2022-10-02 15:34 UTC, Chew approved these changes
Seems good! Gonna do some testing just to be sure.

2022-10-09 14:45 UTC, Chew commented
<img width="257" alt="image" src="https://user-images.githubusercontent.com/8278263/194763195-07e50557-c623-4e49-9df3-e9497bb78de3.png">
Weird, I added the name localization to a parent command, but it didn't take effect for the child. Not sure what's up. Nor did description locale take effect.

2022-10-11 15:20 UTC, ZephyrKaOne commented
> <img alt="image" width="257" src="https://user-images.githubusercontent.com/8278263/194763195-07e50557-c623-4e49-9df3-e9497bb78de3.png">
> 
> Weird, I added the name localization to a parent command, but it didn't take effect for the child. Not sure what's up. Nor did description locale take effect.

Fixed it, now it works.

2022-10-16 14:02 UTC, Chew commented
<img width="238" alt="image" src="https://user-images.githubusercontent.com/8278263/196039682-8064d94d-0fad-4f3b-b121-b994a3e6fa01.png">
Looks great!

2022-10-16 14:03 UTC, merged